# Generated by Django 4.2 on 2024-03-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='post_month',
            new_name='post_date',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_month_2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_month_3',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_month_4',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_month_5',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_month_6',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year_2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year_3',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year_4',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year_5',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='post_year_6',
        ),
    ]
