# Generated by Django 4.2 on 2024-03-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_3',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_4',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_5',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_6',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='description_6',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='title_4',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='title_5',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='title_6',
        ),
    ]
