# Generated by Django 4.2 on 2024-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('our_mission', models.CharField(max_length=500)),
                ('our_vision', models.CharField(max_length=500)),
                ('why_us', models.CharField(max_length=500)),
            ],
        ),
    ]
