# Generated by Django 4.2 on 2024-03-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messages',
            new_name='message',
        ),
    ]
