# Generated by Django 4.2 on 2024-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_3',
            field=models.TextField(null=True),
        ),
    ]
